dist: xenial
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.11.13
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
script:
- "~/tfbin/terraform fmt -write=false -diff=true -check"
notifications:
  email: false
  slack:
    secure: n6CYDKlwGMQ8rIvjF0gIVxUH7z5Gz+9HsjeC9dQjoqQqDaBORJNWNvGD5EpWGwu44qc1zt9mfXv331LWCQqmB2zuNJtlgUyEktu7BSqvjA6B5oF/9v2EsGQneSfG+0AEqu22AVxemF4csc83eBKyZbAv8UZRHIx/cDU+obCHDNHPVhdLDxIiwGilrPHkVefm837DT+WvCsN7deZbY2Ztl8KhMNTpWODSlSjmvhiAYioZoTQ6zsz77WGA3cKJasIEbLFkUvV1WQnpZEWTWlhQCJEvNSlCzja/1gU30gIj/8Um6CsFIrIVzw8E7rE2D2fNpGIH/6c1ddklAff5wlR2Y7w7qX26peFpmJcbUXV5lh7OUZgSGhOnz5Y1O22BiWWGfAWg8zdIPRfRihH9mNb7muzQ6ZaUPBaUZpgImFG9PNohPzYkgj5secSd3E2OWCPO5VicfJG8sPZF7LN3WSKu9fpR1uDKziTF1rh54hglord88Y5ZJFYm40EIhj5I4GNaIWqiPaNWWMBAe7i9Kpyjd6//Hbf11//E9VZSZXTBmZbehqGx9qtHTbxu6WODWDcSo18gQCSDmXIt98F1tMGO5YYXJ8GujbqmFSPYnwdhdtTkytq61R9HWkJkibWaTn3ryuBDy/rRrGIpACXCyBdfqK1XqlTzCaxZqZ9KPoXrHZA=
